/**
 * Stenographer — REST access control
 *
 * The REST API serves transcripts, including whatever secrets people paste
 * into their sessions, so listening on loopback isn't enough on its own: a
 * web page can rebind its own hostname to 127.0.0.1 (DNS rebinding) and read
 * the API same-origin, and any local process can connect. Every request
 * therefore has to:
 *
 * - name an allowed Host: `localhost`, `127.0.0.1`, `[::1]`, the configured
 *   `--rest-host`, or a `--rest-allow-host` (421 otherwise);
 * - carry no Origin, or one on an allowed host (403 otherwise);
 * - carry `Authorization: Bearer <token>` (401 otherwise), unless the
 *   operator started with `--rest-insecure`.
 *
 * The token is the operator's (`restToken`, `STENOGRAPHER_REST_TOKEN`) or
 * one generated on first run into `<state dir>/rest-token` with mode 0600.
 * It keeps out pages and other users, not the operator's own processes: an
 * agent that can read the operator's files can read the token too.
 */

import { randomBytes, timingSafeEqual } from 'node:crypto';
import { chmodSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

export const REST_TOKEN_FILE = 'rest-token';
/** Shortest token accepted from configuration. */
export const MIN_REST_TOKEN_LENGTH = 16;

const LOOPBACK_HOSTS = ['localhost', '127.0.0.1', '[::1]'];
/** Bind addresses that aren't a name anyone sends in Host. */
const WILDCARD_BINDS = new Set(['', '0.0.0.0', '::', '[::]']);
/** What a Host header may contain: a name or address, a port, IPv6 brackets. */
const HOST_HEADER = /^[A-Za-z0-9.\-:[\]]+$/;

export interface RestToken {
  token: string;
  /** Where it is stored; null when configured, or when the state is in memory. */
  path: string | null;
  /** Generated by this call. */
  created: boolean;
}

/** `<state dir>/rest-token`, or null for an in-memory state database. */
export function restTokenPath(statePath: string): string | null {
  if (!statePath || statePath === ':memory:') return null;
  return join(dirname(resolve(statePath)), REST_TOKEN_FILE);
}

function generateToken(): string {
  return randomBytes(32).toString('base64url');
}

/**
 * The bearer token REST requires: the configured one, else the one stored
 * beside the state database, generated (mode 0600) the first time.
 */
export function resolveRestToken(statePath: string, configured?: string): RestToken {
  if (configured !== undefined) {
    if (configured.length < MIN_REST_TOKEN_LENGTH) {
      throw new Error(`the REST token must be at least ${MIN_REST_TOKEN_LENGTH} characters`);
    }
    return { token: configured, path: null, created: false };
  }
  const path = restTokenPath(statePath);
  if (!path) return { token: generateToken(), path: null, created: true };

  const stored = readToken(path);
  if (stored) return { token: stored, path, created: false };
  const token = generateToken();
  try {
    writeFileSync(path, token + '\n', { mode: 0o600, flag: 'wx' });
  } catch (err) {
    // Another process created it first: use theirs
    if ((err as NodeJS.ErrnoException).code === 'EEXIST') {
      const theirs = readToken(path);
      if (theirs) return { token: theirs, path, created: false };
    }
    throw err;
  }
  return { token, path, created: true };
}

function readToken(path: string): string | null {
  let text: string;
  try {
    text = readFileSync(path, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw err;
  }
  // A token others can read is no token: keep it the owner's alone
  if (process.platform !== 'win32' && (statSync(path).mode & 0o077) !== 0) chmodSync(path, 0o600);
  return text.trim() || null;
}

/** Normalizes a configured host the way URL.hostname spells it. */
function normalizeHost(host: string): string {
  const h = host.trim().toLowerCase();
  return h.includes(':') && !h.startsWith('[') ? `[${h}]` : h;
}

/** The host names REST answers to: loopback, plus the bind host and any extras. */
export function allowedHostNames(extra: string[] = []): Set<string> {
  const hosts = new Set(LOOPBACK_HOSTS);
  for (const host of extra) {
    if (!WILDCARD_BINDS.has(host.trim())) hosts.add(normalizeHost(host));
  }
  return hosts;
}

/** The host name a Host header names, or null when it's missing or malformed. */
export function hostHeaderName(header: string | undefined): string | null {
  if (!header || !HOST_HEADER.test(header)) return null;
  try {
    return new URL(`http://${header}`).hostname.toLowerCase();
  } catch {
    return null;
  }
}

/** True when an Origin header (if any) names an allowed host. `null` origins are refused. */
export function originAllowed(origin: string | undefined, allowed: Set<string>): boolean {
  if (origin === undefined) return true;
  try {
    const { protocol, hostname } = new URL(origin);
    return (protocol === 'http:' || protocol === 'https:') && allowed.has(hostname.toLowerCase());
  } catch {
    return false;
  }
}

/** Constant-time check of an `Authorization: Bearer <token>` header. */
export function bearerMatches(expected: string, header: string | undefined): boolean {
  const match = header?.match(/^Bearer\s+(\S+)\s*$/i);
  if (!match) return false;
  const a = Buffer.from(expected);
  const b = Buffer.from(match[1]);
  return a.length === b.length && timingSafeEqual(a, b);
}
